const projects = [
    'PARK MANSION Minami Azabu',
    'with Silence Kawana',
    'Park le JADE SHIROKANE Residence',
    'SEVENS VILLA Karuizawa',
    'HIKAWA GARDENS',
    'ONE AVENUE',
    'CENTURY FOREST',
    'PROUD Rokakoen',
    'PARK MANSION Roppongi',
    'NISHIAZABU RESIDENCE',
    'AZABU GARDENS',
    'THE PARK HOUSE Gran Minamiaoyama',
    'DIANACOURT Bunkyo Hongodai',
    'CLASSY HOUSE Hiroo Fiorire',
    'CLOISTERS Hiroo',
    'F HOUSE',
    'K HOUSE',
    'INOKASHIRA',
    'ITOHPIA jiyugaoka',
    'ATLAS Suwacho Residence',
    'Brillia Hongo Sanchome',
    'FIVE'
];
